default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: arkademy_shop_development
test:
  <<: *default
  database: arkademy_shop_test
production:
  <<: *default
  database: arkademy_shop_production
  username: arkademy_shop
  password: <%= ENV['ARKADEMY_SHOP_DATABASE_PASSWORD'] %>
